name: tbp_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl: "^0.15.2"
  video_player: ^0.10.7
  flutter_lottie: ^0.2.0
  flutter_staggered_grid_view: 
  flutter_staggered_animations: 
  flutter_masked_text:
  cloud_firestore: 
  firebase_core: 
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
      - assets/backgroud_tbp.jpg
      - assets/backgroud.jpg

      - assets/logo_tbp.png
      - assets/logo_tbp2.png
      - assets/video_login.mp4
      - assets/video_login2.mp4
      - assets/footer.jpg
      - assets/logotipo.png

      - assets/icons/megafone.png
      - assets/icons/ingresso.png
      - assets/icons/combo.png
 
  uses-material-design: true